Counterfactual Section
r-causal/causal-inference-in-R pull request #138
Opened 2022-11-04 15:01 UTC by LucyMcGowan

closes #63

2023-02-24 15:42 UTC, tgerke reviewed
This is awesome, love the Ice-T example (SVU who knew?)

Is it possible to put a final touch on the last idea that will lead us more naturally into target trials? It's clear that Spike and Ice-T don't directly mirror each other in possible confounders (talent vs not) but they do in the exposure (LA background). We conclude a population is needed, which makes total sense -- but it may be possible to describe what the ideal population would look like: a mix of talent, a mix of LA background vs not (which, being the exposure, tells us about the need for exposed and unexposed), etc.

2023-02-24 15:42 UTC, tgerke commented on chapters/chapter-04.qmd
> +Perhaps we can find someone else who is exactly like Ice-T who did not make the same decsion and see how they fare.
```suggestion
Perhaps we can find someone else who is exactly like Ice-T who did not make the same decision and see how they fare.
```

2023-02-24 15:42 UTC, tgerke commented on chapters/chapter-04.qmd
> +Now, having this as a concrete example of an attempt to construct a counterfactual scenario in the "real-world" there are several issues that we can immediate see, highlighting the difficulty in draw
```suggestion
Now, having this as a concrete example of an attempt to construct a counterfactual scenario in the "real-world" there are several issues that we can immediately see, highlighting the difficulty in drawing such inference.
```

2023-04-07 14:42 UTC, malcolmbarrett requested changes
I'll probably do some copy edits after you merge but these are the big things

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +Before we talk about *counterfactuals,* let's begin by thinking about the philosophical concept of a *potential outcome.* Prior to some "cause" occurring, for example receiving some exposure, the *po
I think we need a smoother intro here. The reader hasn't really heard much about counterfactuals yet so they don't know we need to deviate from them

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +Only *one* of these potential outcomes will actually be realized, the one corresponding to the exposure that actually occurred, and therefore only one is observable.
Maybe we should have some sort of diagram here to show the hypothetical paths to supplement the text explanation

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +This leaves one potential outcome as *observable* and one *missing.* This is why early causal inference methods were often framed as missing data problems -- we need to make certain assumptions about
```suggestion
In the case of a binary exposure, this leaves one potential outcome as *observable* and one *missing.* In fact, early causal inference methods were often framed as missing data problems; we need to make certain assumptions about the *missing counterfactuals*, the value of the potential outcome corresponding to the exposure(s) that did not occur.
```

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +Ultimately, our causal effect of interest is often some difference in potential outcomes $Y(1) - Y(0)$, averaged over a particular population.
```suggestion
Our causal effect of interest is often some difference in potential outcomes $Y(1) - Y(0)$, averaged over a particular population.
```

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +In causal inference, we attempt to control for all factors that are related to an exposure and outcome such that we can construct a counterfactual outcome that would have occurred in the alternate un
I think this sentence should be split into the two ideas of 1) the alternate universe is what we want to observe 2) but in practice, we can't do that, so we compare similar people with different exposures. I think that will connect to the Ice-T story better

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +This book is attempting a small study, two people who prior to some event were the same and after were different -- Spike's outcomes serve as the counterfactual to Ice-T's.
I think we could use a sentence here connecting to what we need to do in CI:
* In practice, this is what we need to do in CI, ...
* Even randomized trials are limited to a single factual world, so we compare groups
etc

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +First, while the set up implies that the two individuals were similar prior to the precipitating event that dictated their future opposite directions, we can easily identify factors in which perhaps
```suggestion
First, while the synopsis implies that the two individuals were similar prior to the precipitating event that dictated their future opposite directions, we can easily identify factors in which perhaps they differed.
```

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +For example, did Spike have Ice-T's musical talent?
```suggestion
Ice-T decided to leave his life of crime, but that wasn't the only factor in his success: he had enough musical talent to make a career of it. Did Spike have Ice-T's musical talent?
```

2023-04-07 14:42 UTC, malcolmbarrett commented on chapters/chapter-04.qmd
> +Again, this is attempted with Spike, and even so presents challenges.
I think these few sentences need to be reworked a little. Each sentence hits a topic important for the transition to the next few but they are phrased in a way that makes it seems like you're just repeating what you said before

2023-08-04 14:59 UTC, merged